projects:
  Codegen Project:
    schemaPath: db-schemas/schema.gql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 3
extensions:
  amplify:
    version: 3
