import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { AuthSidebar } from "@/components/auth-sidebar";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex h-screen">
      <div className="w-full max-w-[400px] hidden lg:block h-full">
        <AuthSidebar />
      </div>
      <div className="w-full h-full">{children}</div>
      <Toaster />
    </main>
  );
}
