"use client";
import React from "react";
import { TrendingUp } from "lucide-react";
import {
  CartesianGrid,
  Line,
  LineChart,
  XAxis,
  Label,
  Pie,
  PieChart,
} from "recharts";

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ChartConfig,
  ChartContainer,
  ChartTooltip,
  ChartTooltipContent,
  ChartLegend,
  ChartLegendContent,
} from "@/components/ui/chart";
import { compactNumbers } from "@/hooks/useful-functions";

// This is where you will find all the chart data... I think it's organized enough for you to find.
const chartData = [
  {
    month: "January",
    zikiRevenue: 186,
    globalRevenue: 80,
    callerBackRingtones: 180,
  },
  {
    month: "February",
    zikiRevenue: 305,
    globalRevenue: 200,
    callerBackRingtones: 160,
  },
  {
    month: "March",
    zikiRevenue: 237,
    globalRevenue: 120,
    callerBackRingtones: 168,
  },
  {
    month: "April",
    zikiRevenue: 73,
    globalRevenue: 190,
    callerBackRingtones: 200,
  },
  {
    month: "May",
    zikiRevenue: 209,
    globalRevenue: 130,
    callerBackRingtones: 130,
  },
  {
    month: "June",
    zikiRevenue: 214,
    globalRevenue: 140,
    callerBackRingtones: 200,
  },
];

const pieChartData = [
  { browser: "Ziki Revenue", visitors: 275, fill: "var(--color-zikiRevenue)" },
  {
    browser: "Global Revenue",
    visitors: 200,
    fill: "var(--color-globalRevenue)",
  },
  // { browser: "firefox", visitors: 287, fill: "var(--color-firefox)" },
  // { browser: "edge", visitors: 173, fill: "var(--color-edge)" },
  {
    browser: "Caller Back Ringtones",
    visitors: 190,
    fill: "var(--color-callerBackRingtones)",
  },
];

// These are the chart configurations, you can call them schema for all I care.
const chartConfig = {
  zikiRevenue: {
    label: "Ziki Revenue",
    color: "hsl(var(--chart-1))",
  },
  globalRevenue: {
    label: "Global Revenue",
    color: "hsl(var(--chart-2))",
  },

  callerBackRingtones: {
    label: "Caller Back Ringtones",
    color: "hsl(var(--chart-3))",
  },
} satisfies ChartConfig;

const pieChartConfig = {
  zikiRevenue: {
    label: "Ziki Revenue",
    color: "hsl(var(--chart-1))",
  },
  globalRevenue: {
    label: "Global Reveneu",
    color: "hsl(var(--chart-2))",
  },
  callerBackRingtones: {
    label: "Caller Back Ringtones",
    color: "hsl(var(--chart-3))",
  },
} satisfies ChartConfig;

// These are the different chart components... Rather Charts... You catch my drift!
// The chart below is the line chart.
export function SalesChart() {
  return (
    <Card className="h-full w-full">
      <CardHeader>
        <CardTitle className="text-blue-600">Revenue By Month</CardTitle>
        <CardDescription>January - June 2024</CardDescription>
      </CardHeader>
      <CardContent>
        <ChartContainer config={chartConfig}>
          <LineChart
            accessibilityLayer
            data={chartData}
            margin={{
              left: 12,
              right: 12,
            }}
          >
            <CartesianGrid vertical={false} />
            <XAxis
              dataKey="month"
              tickLine={false}
              axisLine={false}
              tickMargin={8}
              tickFormatter={(value) => value.slice(0, 3)}
            />
            <ChartTooltip cursor={false} content={<ChartTooltipContent />} />
            <Line
              dataKey="zikiRevenue"
              type="monotone"
              stroke="var(--color-zikiRevenue)"
              strokeWidth={2}
              dot={false}
            />
            <Line
              dataKey="globalRevenue"
              type="monotone"
              stroke="var(--color-globalRevenue)"
              strokeWidth={2}
              dot={false}
            />
            <Line
              dataKey="callerBackRingtones"
              type="monotone"
              stroke="var(--color-callerBackRingtones)"
              strokeWidth={2}
              dot={false}
            />
            <ChartLegend content={<ChartLegendContent />} />
          </LineChart>
        </ChartContainer>
      </CardContent>
      <CardFooter>
        <div className="flex w-full items-start gap-2 text-sm">
          <div className="grid gap-2">
            <div className="flex items-center gap-2 font-medium leading-none">
              Revenue generated by streams <TrendingUp className="h-4 w-4" />
            </div>
          </div>
        </div>
      </CardFooter>
    </Card>
  );
}

// This is the piechart
export function RevenueDistributionChart() {
  const totalVisitors = React.useMemo(() => {
    return pieChartData.reduce((acc, curr) => acc + curr.visitors, 0);
  }, []);
  return (
    <Card className="flex flex-col h-full w-full">
      <CardHeader className="items-center pb-0">
        <CardTitle className="text-blue-600">Revenue Distribution</CardTitle>
        <CardDescription>January - June 2024</CardDescription>
      </CardHeader>
      <CardContent className="flex-1 pb-0">
        <ChartContainer
          config={pieChartConfig}
          className="mx-auto aspect-square max-h-[250px]"
        >
          <PieChart>
            <ChartTooltip
              cursor={false}
              content={<ChartTooltipContent hideLabel />}
            />
            <Pie
              data={pieChartData}
              dataKey="visitors"
              nameKey="browser"
              innerRadius={60}
              strokeWidth={5}
            >
              <Label
                content={({ viewBox }) => {
                  if (viewBox && "cx" in viewBox && "cy" in viewBox) {
                    return (
                      <text
                        x={viewBox.cx}
                        y={viewBox.cy}
                        textAnchor="middle"
                        dominantBaseline="middle"
                      >
                        <tspan
                          x={viewBox.cx}
                          y={viewBox.cy}
                          className="fill-foreground text-3xl font-bold"
                        >
                          {compactNumbers(totalVisitors)}
                        </tspan>
                        <tspan
                          x={viewBox.cx}
                          y={(viewBox.cy || 0) + 24}
                          className="fill-muted-foreground"
                        >
                          Revenue Streams
                        </tspan>
                      </text>
                    );
                  }
                }}
              />
            </Pie>
            {/* <ChartLegend
              content={<ChartLegendContent nameKey="zikiRevenue" />}
              className="-transalte-y-2 flex-wrap gap-2 *:basis-1/4 *:justify-center"
            /> */}
          </PieChart>
        </ChartContainer>
      </CardContent>
      <CardFooter className="flex-col gap-2 text-sm">
        <div className="leading-none text-muted-foreground">
          Showing total revenue distribution for the last 6 months
        </div>
      </CardFooter>
    </Card>
  );
}
